import {
  DomExtractionTools,
  HistoryApiTools,
  ScriptingApiTools,
  StorageApiTools,
  TabGroupsApiTools,
  TabsApiTools,
  WindowsApiTools,
} from '@mcp-b/extension-tools';

export const chromeApiBuiltInTools = {
  // bookmarks: {
  //   name: 'Bookmarks',
  //   namespace: 'Bookmarks',
  //   instance: BookmarksApiTools,
  //   allowedDomains: ['<all_urls>'],
  //   inputSchema: {},
  //   description: '',
  //   enabled: true,
  //   isBuiltIn: true,
  //   isExtension: true,
  // },
  dom_extraction: {
    name: 'Dom Extraction',
    namespace: 'chrome_api',
    allowedDomains: ['<all_urls>'],
    instance: DomExtractionTools,
    inputSchema: {},
    description:
      'Extracts high-level structural overview of the page. This is the first step for AI agents to understand page layout.',
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  history: {
    name: 'History',
    namespace: 'chrome_api',
    instance: HistoryApiTools,
    allowedDomains: ['<all_urls>'],
    description: 'Performs operations on the Chrome History API',
    inputSchema: {},
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  scripting: {
    name: 'Scripting',
    namespace: 'chrome_api',
    instance: ScriptingApiTools,
    allowedDomains: ['<all_urls>'],
    inputSchema: {},
    description:
      'Executes JavaScript code in a specific tab using chrome.scripting API. Limited by CSP restrictions. If no tabId is specified, operates on the currently active tab',
    options: {
      executeScript: true,
      executeUserScript: true,
      insertCSS: false,
      removeCSS: false,
    },
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  storage: {
    name: 'Storage',
    namespace: 'chrome_api',
    instance: StorageApiTools,
    allowedDomains: ['<all_urls>'],
    description: 'Performs operations on Chrome storage API',
    inputSchema: {},
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  tab_group: {
    name: 'Tab Groups',
    namespace: 'chrome_api',
    instance: TabGroupsApiTools,
    allowedDomains: ['<all_urls>'],
    description: 'Performs operations on tab groups using Chrome TabGroups API',
    inputSchema: {},
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  tabs: {
    name: 'Tabs',
    namespace: 'chrome_api',
    instance: TabsApiTools,
    allowedDomains: ['<all_urls>'],
    description: 'Performs various tab operations using the Chrome Tabs API',
    inputSchema: {},
    options: {
      getAllTabs: true,
      createTab: true,
      closeTabs: true,
      updateTab: true,
    },
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  windows: {
    name: 'Windows',
    namespace: 'chrome_api',
    instance: WindowsApiTools,
    allowedDomains: ['<all_urls>'],
    inputSchema: {},
    description: 'Performs operations on browser windows.',
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
};

export const ToolNameMap = {
  window_parameters_description: 'Windows',
  window_operations: 'Windows',
  tab_group_parameters_description: 'Tab Group',
  tab_group_operations: 'Tab Group',
  tab_parameters_description: 'Tab',
  tab_operations: 'Tab',
  history_parameters_description: 'History',
  history_operations: 'History',
  bookmark_parameters_description: 'Bookmark',
  bookmark_operations: 'Bookmark',
  storage_parameters_description: 'Storage',
  storage_operations: 'Storage',
  dom_extract_region: 'DOM Extraction',
  dom_extract_content: 'DOM Extraction',
  dom_extract_structure: 'DOM Extraction',
  execute_script: 'Scripting',
  execute_user_script: 'Scripting',
  execute_user_script_legacy: 'Scripting',
  insert_css: 'Scripting',
  remove_cs: 'Scripting',
  check_available_apis: 'API Check',
};

export type keys = keyof typeof chromeApiBuiltInTools;
