import {
  BookmarksApiTools,
  DomExtractionTools,
  HistoryApiTools,
  ScriptingApiTools,
  StorageApiTools,
  TabGroupsApiTools,
  TabsApiTools,
  WindowsApiTools,
} from '@mcp-b/extension-tools';

export const builtInTools = {
  bookmarks: {
    name: 'Bookmarks',
    namespace: 'Bookmarks',
    instance: BookmarksApiTools,
    allowedDomains: ['<all_urls>'],
    inputSchema: {},
    description: '',
    enabled: true,
    isBuiltIn: true,
  },
  domExtraction: {
    name: 'Dom Extraction',
    namespace: 'Dom Extraction',
    allowedDomains: ['<all_urls>'],
    instance: DomExtractionTools,
    inputSchema: {},
    description: '',
    enabled: true,
    isBuiltIn: true,
  },
  history: {
    name: 'History',
    namespace: 'History',
    instance: HistoryApiTools,
    allowedDomains: ['<all_urls>'],
    description: '',
    inputSchema: {},
    enabled: true,
    isBuiltIn: true,
  },
  scripting: {
    name: 'Scripting',
    namespace: 'Scripting',
    instance: ScriptingApiTools,
    allowedDomains: ['<all_urls>'],
    inputSchema: {},
    description: '',
    options: {
      executeScript: true,
      executeUserScript: true,
      insertCSS: false,
      removeCSS: false,
    },
    enabled: true,
    isBuiltIn: true,
  },
  storage: {
    name: 'Storage',
    namespace: 'Storage',
    instance: StorageApiTools,
    allowedDomains: ['<all_urls>'],
    description: '',
    inputSchema: {},
    enabled: true,
    isBuiltIn: true,
  },
  tabGroups: {
    name: 'Tab Groups',
    namespace: 'Tab Groups',
    instance: TabGroupsApiTools,
    allowedDomains: ['<all_urls>'],
    description: '',
    inputSchema: {},
    enabled: true,
    isBuiltIn: true,
  },
  tabs: {
    name: 'Tabs',
    namespace: 'Tabs',
    instance: TabsApiTools,
    allowedDomains: ['<all_urls>'],
    description: '',
    inputSchema: {},
    options: {
      getAllTabs: true,
      createTab: true,
      closeTabs: true,
      updateTab: true,
    },
    enabled: true,
    isBuiltIn: true,
  },
  windows: {
    name: 'Windows',
    namespace: 'Windows',
    instance: WindowsApiTools,
    allowedDomains: ['<all_urls>'],
    inputSchema: {},
    description: '',
    enabled: true,
    isBuiltIn: true,
  },
};

export type keys = keyof typeof builtInTools;
