import {
  BookmarksApiTools,
  DomExtractionTools,
  HistoryApiTools,
  ScriptingApiTools,
  StorageApiTools,
  TabGroupsApiTools,
  TabsApiTools,
  WindowsApiTools,
} from '@mcp-b/extension-tools';

export const builtInTools = {
  bookmarks: {
    name: 'Bookmarks',
    namespace: 'Bookmarks',
    instance: BookmarksApiTools,
    allowedDomains: ['<all_urls>'],
    inputSchema: {},
    description: '',
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  dom_extraction: {
    name: 'Dom Extraction',
    namespace: 'Dom Extraction',
    allowedDomains: ['<all_urls>'],
    instance: DomExtractionTools,
    inputSchema: {},
    description: '',
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  history: {
    name: 'History',
    namespace: 'History',
    instance: HistoryApiTools,
    allowedDomains: ['<all_urls>'],
    description: '',
    inputSchema: {},
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  scripting: {
    name: 'Scripting',
    namespace: 'Scripting',
    instance: ScriptingApiTools,
    allowedDomains: ['<all_urls>'],
    inputSchema: {},
    description: '',
    options: {
      executeScript: true,
      executeUserScript: true,
      insertCSS: false,
      removeCSS: false,
    },
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  storage: {
    name: 'Storage',
    namespace: 'Storage',
    instance: StorageApiTools,
    allowedDomains: ['<all_urls>'],
    description: '',
    inputSchema: {},
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  tab_group: {
    name: 'Tab Groups',
    namespace: 'Tab Groups',
    instance: TabGroupsApiTools,
    allowedDomains: ['<all_urls>'],
    description: '',
    inputSchema: {},
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  tabs: {
    name: 'Tabs',
    namespace: 'Tabs',
    instance: TabsApiTools,
    allowedDomains: ['<all_urls>'],
    description: '',
    inputSchema: {},
    options: {
      getAllTabs: true,
      createTab: true,
      closeTabs: true,
      updateTab: true,
    },
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
  windows: {
    name: 'Windows',
    namespace: 'Windows',
    instance: WindowsApiTools,
    allowedDomains: ['<all_urls>'],
    inputSchema: {},
    description: '',
    enabled: true,
    isBuiltIn: true,
    isExtension: true,
  },
};

export const ToolNameMap = {
  window_parameters_description: 'Windows',
  window_operations: 'Windows',
  tab_group_parameters_description: 'Tab Group',
  tab_group_operations: 'Tab Group',
  tab_parameters_description: 'Tab',
  tab_operations: 'Tab',
  history_parameters_description: 'History',
  history_operations: 'History',
  bookmark_parameters_description: 'Bookmark',
  bookmark_operations: 'Bookmark',
  storage_parameters_description: 'Storage',
  storage_operations: 'Storage',
  dom_extract_region: 'DOM Extraction',
  dom_extract_content: 'DOM Extraction',
  dom_extract_structure: 'DOM Extraction',
  execute_script: 'Scripting',
  execute_user_script: 'Scripting',
  execute_user_script_legacy: 'Scripting',
  insert_css: 'Scripting',
  remove_cs: 'Scripting',
  check_available_apis: 'API Check',
};

export type keys = keyof typeof builtInTools;
